name: Scala CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - name: Set up Scala and sbt
        uses: coursier/setup-action@v1
        with:
          apps: sbt scala scalafmt

      - name: Run tests
        run: sbt test
